config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :friendships, only: %i[create update destroy show]
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :profiles, only: %i[index show] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :accepted_friend, -> { where('status = ?', 1) }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def show
    @accepted_friendships = Friendship.where(user_id: params[:id]).where(status: 1)
    @requested_friends = Friendship.where(user_id: params[:id]).where(status: 2)
    @friend_requests = Friendship.where(friend_id: params[:id]).where(status: 2)
    @user = User.find(params[:id])
  end

  # POST /friendships or /friendships.json
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id], status: 2)

    respond_to do |format|
      if @friendship.save
        format.html { redirect_back(fallback_location: root_url) }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @friendship = current_user.inverse_friendships.where(user_id: params[:user_id])
    respond_to do |format|
      if @friendship.first.update(status: 1)
        Friendship.create(user_id: @friendship.first.friend_id, friend_id: @friendship.first.user_id, status: 1)
        format.html { redirect_back(fallback_location: root_url) }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:friend_id])
    @friendship2 = current_user.inverse_friendships.where(user_id: params[:friend_id])
    unless @friendship.empty?
      @friendship.destroy(@friendship.first.id)
    end
    unless @friendship2.empty?
      @friendship2.destroy(@friendship2.first.id)
    end

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.json { head :no_content }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship) do |form| %>
  <% if friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :friend_id, style: "display: block" %>
    <%= form.number_field :friend_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :create, style: "display: block" %>
    <%= form.text_field :create %>
  </div>

  <div>
    <%= form.label :destroy, style: "display: block" %>
    <%= form.text_field :destroy %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
<div class="container p-4 d-flex flex-column justify-content-center align-items-start" >
  <div class="row align-items-center justify-content-center d-flex">
    <% if user.profile_picture.attached? && user.profile_picture.representable? %>
      <div class="col flex-grow-0">
        <%= link_to image_tag(user.profile_picture, :size => '50x50', class: "rounded-circle"), profile_url(id: user.id) %>
      </div>
    <% else %>
      <div class="col flex-grow-0">
        <%= link_to image_tag('account-circle-outline.svg', :size => '50x50', class: "rounded-circle"), profile_url(id: user.id) %>
      </div>
    <% end %>
    <div class="col">
      <%= link_to "#{user.full_name}", profile_url(id: user.id), class: "btn text-white text-nowrap" %>
    </div>
  </div>
</div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friendships</h1>

<div id="friendships">
  <% @friendships.each do |friendship| %>
    <%= render friendship %>
  <% end %>
</div>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<% if current_user == @user%>
  <div class="row">
    <div class="col">
      <h2 class="text-white">My Friends</h2>
      <% @accepted_friendships.each do |friend| %>
        <div class="row align-items-center">
          <div class="col">
            <%= render partial: 'friendship', locals: {user: friend.friend} %>
          </div>
          <div class="col flex-grow-0 pe-5">
            <%= button_to "Delete Friend", friendship_path(user_id: friend.user_id, friend_id: friend.friend_id), method: :delete, class: "btn text-white btn-danger text-nowrap" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col">
      <h2 class="text-white">Friend Requests</h2>
      <% @friend_requests.each do |friend| %>
        <div class="row align-items-center">
          <div class="col">
            <%= render partial: 'friendship', locals: {user: friend.user} %>
          </div>
          <div class="col flex-grow-0 pe-5">
            <%= button_to "Accept Request", friendship_path(user_id: friend.user_id, friend_id: friend.friend_id), method: :patch, class: "btn text-white btn-success text-nowrap" %>
            <%= button_to "Decline Request", friendship_path(user_id: friend.user_id, friend_id: friend.friend_id), method: :delete, class: "btn text-white btn-danger text-nowrap" %>
          </div>
          <div class="col flex-grow-0 pe-5">
          </div>
        </div>
      <% end %>
    </div>
    <div class="col">
      <h2 class="text-white">Friends Requested</h2>
      <% @requested_friends.each do |friend| %>
        <div class="row align-items-center">
          <div class="col">
            <%= render partial: 'friendship', locals: {user: friend.friend} %>
          </div>
          <div class="col flex-grow-0 pe-5">
            <%= button_to "Delete Request", friendship_path(user_id: friend.user_id, friend_id: friend.friend_id), method: :delete, class: "btn text-white btn-danger text-nowrap" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col">
      <h2 class="text-white"><%= @user.full_name %>'s Friends</h2>
      <% @accepted_friendships.each do |friend| %>
        <div class="row align-items-center">
          <div class="col">
            <%= render partial: 'friendship', locals: {user: friend.friend} %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>