config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :friendships, only: %i[create update destroy show]
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :profiles, only: %i[index show] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :reactions, as: :reactionable

  has_one_attached :picture, dependent: :destroy
  validates :picture, content_type: %i[png jpg jpeg]

  validates :title, presence: true
  validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    # or(Post.where(user_id: current_user.friendships.accepted_friend.user_id))
    @post = Post.new
    @posts = Post.where(user_id: current_user.id).or(Post.where(user_id: current_user.friendships.where(status: 1).map {|friend| friend.friend_id})).order(created_at: :desc).includes(:comments)
    @friends = Friendship.where(user_id: current_user.friend_ids).where(status: 1)
    @who_to_follow = User.limit(5).where.not(user_id: current_user.friend_ids).order("RANDOM()")
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_back(fallback_location: root_url) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_back(fallback_location: root_url) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :picture)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |f| %>
  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="row pt-3 pb-2">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title...' %>
  </div>
  <div class="row pb-2">
    <%= f.text_area :content, class: 'form-control', placeholder: 'Share your thoughts!' %>
  </div>
  <div class="row pb-2">
    <%= f.label :picture, 'Upload a picture!' %>
    <%= f.file_field :picture, class:'form-control' %>
  </div>
  <div class="row">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_friend_profile.html.erb
<div class="container p-4 d-flex flex-column justify-content-center align-items-start" >
  <div class="row align-items-center d-flex pb-4">
    <% if user.profile_picture.attached? && user.profile_picture.representable? %>
      <div class="col flex-grow-0">
        <%= link_to image_tag(user.profile_picture, :size => '50x50', class: "rounded-circle"), profile_url(id: user.id) %>
      </div>
    <% else %>
      <div class="col flex-grow-0">
        <%= link_to image_tag('account-circle-outline.svg', :size => '35x35', class: "rounded-circle"), profile_url(id: user.id) %>
      </div>
    <% end %>
    <div class="col">
      <%= link_to "#{user.full_name}", profile_url(id: user.id), class: "btn text-white" %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <div class="row align-items-center d-flex pt-2">
    <div class="col flex-grow-0">
      <% if post.user.profile_picture.attached? && post.user.profile_picture.representable?%>
        <%= link_to image_tag(post.user.profile_picture, :size => '50x50', class: "rounded-circle"), profile_url(id: post.user.id) %>
      <% else %>
        <%= link_to image_tag('account-circle-outline.svg', :size => '50x50', class: "rounded-circle"), profile_url(id: post.user.id) %>
      <% end %>
    </div>
    <div class="col">
      <div class="align-self-bottom">
        <%= link_to post.user.full_name, profile_url(id: post.user.id), class: "btn text-black" %>
      </div>
    </div>
  </div>
  <div class="row">
    <h3><%= post.title %></h2>
  </div>
  <div class="row">
    <p><%= post.content %></p>
  </div>
  <% if post.picture.attached? && post.picture.representable? %>
    <div class="row pb-2">
      <%= image_tag(post.picture) %>
    </div>
  <% end %>
  <div class="row">
    <%= form_with(model: [post, post.comments.build]) do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :post_id, :vlaue => post.id %>
      <div class="col">
        <div class="form-group pb-3">
          <%= f.text_field :content, class: 'form-control', placeholder: 'Write a comment...' %>
        </div>
      </div>
      <div class="col">
        <%= f.submit "Save", class: 'btn btn-success' %>  
      </div>
    <% end %>
  </div>
  <div class="row g-1 pt-2">
    <div class="col flex-grow-0 text-nowrap">
      <% if post.reactions.map {|reaction| reaction.user_id}.include?(current_user.id)%>
        <%= button_to image_tag('thumb-up-outline.svg', :size => '20x20') + " #{post.reactions.where(reaction_type: 1).count}", reaction_path(reaction: {user_id: current_user.id, reaction_type: 1}, post_id: post.id, id: post.reactions.where(user_id: current_user.id).first.id), method: :delete, class: 'btn'%>
      <% else %>
        <%= button_to image_tag('thumb-up-outline.svg', :size => '20x20') + " #{post.reactions.where(reaction_type: 1).count}", reactions_path(reaction: {user_id: current_user.id, reaction_type: 1}, post_id: post.id), class: 'btn'%>
      <% end %>
    </div>
    <div class="col">
      <% if post.reactions.map {|reaction| reaction.user_id}.include?(current_user.id)%>
        <%= button_to image_tag('thumb-down-outline.svg', :size => '20x20') + " #{post.reactions.where(reaction_type: 2).count}", reaction_path(reaction: {user_id: current_user.id, reaction_type: 2}, post_id: post.id, id: post.reactions.where(user_id: current_user.id).first.id), method: :delete, class: 'btn'%>
      <% else %>
        <%= button_to image_tag('thumb-down-outline.svg', :size => '20x20') + " #{post.reactions.where(reaction_type: 2).count}", reactions_path(reaction: {user_id: current_user.id, reaction_type: 2}, post_id: post.id), class: 'btn'%>
      <% end %>
    </div>
    <div class="col flex-grow-0">
      <% if current_user == post.user %>
        <%= button_to image_tag('trash-can-outline.svg', :size => '20x20'), post_path(id: post.id), method: :delete, class: 'btn'%>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% unless post.comments.empty? %>
      <%= render post.comments.scope %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col">
      <%= render partial: 'shared/profile', locals: {user: current_user} %>    
    </div>
    <div class="col">
      <div class="row">
        <div>
          <div class="bg-light rounded-3 pb-3 mb-3">
            <div class="container">
              <%= render 'form' %>
            </div>        
          </div>
        </div>          
      </div>
      <div class="row">
        <%= render 'shared/feed' %>
      </div>
      
    </div>
    <div class="col">
      <% unless current_user.friendships.accepted_friend.empty?%>
        <div class="container">
          <div class="row">
            <h2 class="text-white">
              Friends
            </h2>          
          </div>
        </div>
        <%= render 'shared/friends' %>
      <% end %>
    </div>
  </div>
</div>



<%# <%= render 'who-to-follow' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>